// The app's API type surface. The tygo-generated types (types.gen.ts,
// regenerated by `task gen:types`) are the source of truth; this file only
// re-exports them under the names the console uses, so a Go struct change flows
// through regeneration rather than a hand edit.

export type {
  ErrorResponse,
  HealthResponse as Health,
  Scope,
  Source,
  ClaimListItem,
  ClaimListResponse as ClaimList,
  EvidenceItem as Evidence,
  ClaimDetail,
  RecallResponse,
  RecalledClaim,
  Contribution as ArmContribution,
  RecallTimings,
} from './types.gen';
