// Code generated by tygo. DO NOT EDIT.
/* generated by tygo; do not edit. Regenerate with `task gen:types`. */

//////////
// source: api.go
/*
Package api is the CRED web console's HTTP surface: plain Gin handlers over
typed request and response structs. It is a projection over the store, not a
second model — the store returns rows and internal/acl decides what a
principal may see, exactly as the CLI does. An endpoint that returned a claim
its caller may not read would be the access-control failure, now over HTTP.
*/


//////////
// source: claims.go


//////////
// source: recall.go

/**
 * RecallQuery is the query string of GET /api/recall.
 */
export interface RecallQuery {
  q: string;
  limit: number /* int */;
  depth: number /* int */;
  budget: number /* int */;
}
/**
 * Contribution is what one retrieval arm added to a claim's fused rank: the
 * arm's name, the rank it gave the claim, its raw score, and the reciprocal-rank
 * points that rank contributed. It is the per-arm reason a result placed where
 * it did.
 */
export interface Contribution {
  arm: string;
  rank: number /* int */;
  raw: number /* float64 */;
  score: number /* float64 */;
}
/**
 * RecalledClaim is one recall result carrying why it ranked.
 */
export interface RecalledClaim {
  id: string;
  statement: string;
  kind: string;
  scope: Scope;
  status: string;
  source?: Source;
  score: number /* float64 */;
  tokens: number /* int */;
  contributions: Contribution[];
}
/**
 * RecallTimings is where a recall's latency went, per arm, in milliseconds.
 */
export interface RecallTimings {
  embed_ms: number /* float64 */;
  dense_ms: number /* float64 */;
  lexical_ms: number /* float64 */;
  load_ms: number /* float64 */;
  total_ms: number /* float64 */;
}
/**
 * RecallResponse is the body of GET /api/recall: the ranked claims plus the
 * retrieval accounting that explains them. Candidates is what fusion saw,
 * Authorized is what survived access control, and OmittedForBudget is what the
 * token ceiling dropped — reported so a short result is never a silent one.
 */
export interface RecallResponse {
  query: string;
  claims: RecalledClaim[];
  candidates: number /* int */;
  authorized: number /* int */;
  omitted_for_budget: number /* int */;
  tokens_used: number /* int */;
  token_budget: number /* int */;
  dominant_arm: string;
  dominant_share: number /* float64 */;
  as_of: string;
  staleness_seconds: number /* float64 */;
  timings: RecallTimings;
}

//////////
// source: types.go

/**
 * ErrorResponse is the body of every non-2xx JSON response.
 */
export interface ErrorResponse {
  error: string;
}
/**
 * HealthResponse reports liveness and the resolved caller identity, so the
 * console can show who it is acting as before any data loads.
 */
export interface HealthResponse {
  status: string;
  version: string;
  principal: string;
}
/**
 * Scope narrows where a claim applies.
 */
export interface Scope {
  kind: string;
  value: string;
}
/**
 * Source locates the evidence a claim rests on within a repository.
 */
export interface Source {
  kind: string;
  repo: string;
  path: string;
  line_start: number /* int */;
  line_end: number /* int */;
  symbol_path: string;
}
/**
 * ClaimListQuery is the query string of GET /api/claims.
 */
export interface ClaimListQuery {
  status: string;
  scope_kind: string;
  scope_value: string;
  limit: number /* int */;
  offset: number /* int */;
}
/**
 * ClaimListItem is one row in the claims browser.
 */
export interface ClaimListItem {
  id: string;
  statement: string;
  kind: string;
  scope: Scope;
  status: string;
  source?: Source;
  contributed_by: string;
  recorded_at: string;
  valid_from: string;
  valid_until: string;
  superseded_at: string;
}
/**
 * ClaimListResponse is the body of GET /api/claims.
 */
export interface ClaimListResponse {
  claims: ClaimListItem[];
  limit: number /* int */;
  offset: number /* int */;
  count: number /* int */;
}
/**
 * EvidenceItem is one piece of evidence under a claim, with its anchor state.
 */
export interface EvidenceItem {
  id: string;
  kind: string;
  repo: string;
  path: string;
  line_start: number /* int */;
  line_end: number /* int */;
  symbol_path: string;
  anchor: string;
}
/**
 * ClaimDetail is the body of GET /api/claims/:id.
 */
export interface ClaimDetail {
  id: string;
  statement: string;
  kind: string;
  scope: Scope;
  status: string;
  confidence: number /* float64 */;
  contributed_by: string;
  source_repo: string;
  recorded_at: string;
  valid_from: string;
  valid_until: string;
  superseded_at: string;
  expired_reason: string;
  evidence: EvidenceItem[];
}
